# Simple makefile to build inih as a static library using g++

CSRC = ../ini.c
CPPSRC = ../cpp/INIReader.cpp
OBJ = $(CSRC:.c=.o) $(CPPSRC:.cpp=.o)
OUT = libinih.a
INCLUDES = -I..
CCFLAGS = -g -O2
CC = g++

default: $(OUT)

.c.o:
	$(CC) $(INCLUDES) $(CCFLAGS) $(EXTRACCFLAGS) -c $< -o $@

$(OUT): $(OBJ)
	ar rcs $(OUT) $(OBJ) $(EXTRAARFLAGS)

clean:
	rm -f $(OBJ) $(OUT)
